repos:
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.5.1'
      hooks:
        - id: mypy
          language: system
          pass_filenames: false
          args: ['cunumeric']
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
            - id: isort
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
            - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
            - id: flake8
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v16.0.6'  # Use the sha / tag you want to point at
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|cc|inl)$
          types_or: []
    - repo: local
      hooks:
        - id: enforce-boilerplate
          name: Enforce boilerplate
          description: Make sure tests include required boilerplate
          entry: python scripts/hooks/enforce_boilerplate.py
          language: python
          pass_filenames: false

ci:
    skip: [mypy]
    autoupdate_schedule: quarterly

default_language_version:
    python: python3
